name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dracula&custom_title=%E5%A5%87%E8%91%A9%E3%81%AE%E7%81%B5%E6%A2%A6&count_private=true&show=reviews,prs_merged,prs_merged_percentage&locale=cn
          path: profile/stats.svg

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&locale=cn&layout=compact&hide_border=true&langs_count=12&size_weight=0.7&count_weight=0.3&hide=CSV
          path: profile/top-langs.svg

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
    
